# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SQFitnessProgram' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SQFitnessProgram
  pod 'SqliteComponent', :path => './SqliteComponent'

end

target 'SQFitnessProgram_Viper' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
    
    # Pods for SQFitnessProgram
    pod 'Viper', :path => './Viper'
    pod 'SqliteComponent', :path => './SqliteComponent'
    
end
