# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SQMagnet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SQMagnet
  pod 'AFNetworking', '~> 3.0'
  pod 'MJExtension'
  pod 'YYWebImage'
  pod 'YYImage/WebP'
  
end
