# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Network' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'SDWebImage'
  pod 'MJExtension'
  pod 'SSZipArchive'
  pod 'AFNetworking'
  pod 'Aspects'
  
  # Pods for Network

end
